### ISSUE TITLE
switch from d3network to networkD3

### ISSUE THREAD

**Issue by cjyetman** [SachaEpskamp/qgraph#10]
[d3Network](https://github.com/christophergandrud/d3Network) was deprecated 2.5 years ago and development moved to [networkD3](https://github.com/christophergandrud/networkD3). I'd be willing to help you convert your `qgraphD3` function to use `networkD3`, though it looks like `qgraphD3` is not exported nor mentioned anywhere else. Any interest?

**Comment by SachaEpskamp** [comment]
Hi, 

Thank you and sorry for the (very) late reply... That would be very interesting! I never really finished this work so would be nice to make this functionality. Perhaps you can contact me by email?

Best, Sacha
