### ISSUE TITLE
Correlations between two different set of variables

### ISSUE THREAD

**Issue by llrs** [SachaEpskamp/qgraph#12]
I am trying to plot the correlation between two set of variables, however I can't.  
The problem arises from the check of `(nrow(input) != ncol(input))` because I don't have the same number of variables for each set.

A reproducible example would be:
```r
m <- matrix(runif(45, -1, 1), ncol = 9, nrow = 5)
qqgraph(m, graph = "cor")
```

Is there any workaround ?

**Comment by SachaEpskamp** [comment]
Hi, 

qgraph expects a correlation matrix here. Perhaps you want to try estimateNetwork from bootnet that wraps around qgraph to do this by default.

**Comment by llrs** [comment]
Many thanks, I tried with a square correlation matrix, but I got an error.

```r
m <- matrix(runif(25, -1, 1), ncol = 5, nrow = 5)
qgraph(m, graph = "cor")
## Error in eigen(input)$values > 0 : invalid comparison with complex values
```
