### ISSUE TITLE
Trying to use a map as a graph background using qgraph

### ISSUE THREAD

**Issue by jabiologo** [SachaEpskamp/qgraph#14]
Hi Sacha and others:

I wonder if there is any way to use a user specific plot as a background in a graph. Specifically, I'm trying to use latitude and longitude coordinates to put the graph nodes over a map... However I'm unable to use a map as a underling picture...

Any idea?

Cheers

**Comment by SachaEpskamp** [comment]
Try this!

https://gist.github.com/SachaEpskamp/442f9ca7c1ed2286d13b3a5a820e8f5c
