### ISSUE TITLE
error in installing the packages

### ISSUE THREAD

**Issue by chloelulu** [SachaEpskamp/qgraph#17]
Hi, 
May I know the issue below? I cannot install this package. May I have yoru help?
Thanks.

> install.packages("qgraph",type="source")
also installing the dependency ‘BDgraph’
trying URL 'https://cran.rstudio.com/src/contrib/BDgraph_2.51.tar.gz'
Content type 'application/x-gzip' length 2283912 bytes (2.2 MB)
downloaded 2.2 MB
trying URL 'https://cran.rstudio.com/src/contrib/qgraph_1.5.tar.gz'
Content type 'application/x-gzip' length 243083 bytes (237 KB)
downloaded 237 KB

* installing *source* package ‘BDgraph’ ...
** package ‘BDgraph’ successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -std=gnu++11 accepts -g... yes
checking for clang++ -std=gnu++11 option to support OpenMP... unsupported
configure: creating ./config.status
config.status: creating src/Makevars
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c BDgraph_init.c -o BDgraph_init.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c MyLapack.cpp -o MyLapack.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c bd_for_ts.cpp -o bd_for_ts.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c check_nthread.cpp -o check_nthread.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c check_os.cpp -o check_os.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c copula.cpp -o copula.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c gcgm_DMH.cpp -o gcgm_DMH.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c gcgm_bd.cpp -o gcgm_bd.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c ggm_DMH.cpp -o ggm_DMH.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c ggm_bd.cpp -o ggm_bd.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c ggm_mpl_bd.cpp -o ggm_mpl_bd.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c gm_mpl_Hill_Climb.cpp -o gm_mpl_Hill_Climb.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c gm_mpl_bd_dis.cpp -o gm_mpl_bd_dis.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c gm_rj.cpp -o gm_rj.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c matrix.cpp -o matrix.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c omp_set_num_cores.cpp -o omp_set_num_cores.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2 -c rgwish.cpp -o rgwish.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o BDgraph.so BDgraph_init.o MyLapack.o bd_for_ts.o check_nthread.o check_os.o copula.o gcgm_DMH.o gcgm_bd.o ggm_DMH.o ggm_bd.o ggm_mpl_bd.o gm_mpl_Hill_Climb.o gm_mpl_bd_dis.o gm_rj.o matrix.o omp_set_num_cores.o rgwish.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [BDgraph.so] Error 1
ERROR: compilation failed for package ‘BDgraph’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/BDgraph’
Warning in install.packages :
  installation of package ‘BDgraph’ had non-zero exit status
ERROR: dependency ‘BDgraph’ is not available for package ‘qgraph’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/qgraph’
Warning in install.packages :
  installation of package ‘qgraph’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/jb/324x34fd61ng6j5qf5kdrsfr0000gn/T/Rtmprx3vRc/downloaded_packages’

**Comment by dpmoriarity** [comment]
I am having a similar issue.

![image](https://user-images.githubusercontent.com/41660395/43178043-627eecd8-8f99-11e8-8763-f92ee5fe85d0.png)

**Comment by SachaEpskamp** [comment]
Did you update R to the latest version?
