### ISSUE TITLE
centralityPlot error with 1.6

### ISSUE THREAD

**Issue by desphua** [SachaEpskamp/qgraph#24]
After updating to qgraph 1.6, I'm having errors with centralityPlot. I didn't have any problems generating the plot in 1.5.

Error in centralityTable(..., standardized = standardized, labels = labels,  : 
  (list) object cannot be coerced to type 'double'

**Comment by SachaEpskamp** [comment]
Do you have an example code?

**Comment by desphua** [comment]
centralityPlot(list(
  network1 = qnetwork.pretest,
  network2 = qnetwork.posttest),
  include = c("Strength", "Betweenness", "Closeness", "ExpectedInfluence"),
  decreasing = TRUE
  )

**Comment by SachaEpskamp** [comment]
This has now been fixed in the devel version!
