### ISSUE TITLE
contralityPlot: include = "all" does not work

### ISSUE THREAD

**Issue by jhoelt** [SachaEpskamp/qgraph#27]
Hi Sacha,

I just installed the devel version of qgraph in order to compare different networks with the centralityPlot function. This is the code: _centralityPlot(list(network1, network2, include = "all"))_

When I don´t use the include = "all" command it gives me only strength for both, but when I use it I get the following error:

_Error in UseMethod("getWmat") : 
  no applicable method for 'getWmat' applied to an object of class "character"_

When I use _centralityPlot(list(network1, network2), include ="ALL")_ it gives me the following error: _Error: Faceting variables must have at least one value_

I also tried _centralityPlot(list(network1, network2, include = c("Strength", "Closeness","Betweenness","ExpectedInfluence")))_ which gives me
_Error in UseMethod("getWmat") : 
  no applicable method for 'getWmat' applied to an object of class "character"_
again.

But I would also like to have at least betweenness and closeness in the graph, too.

When I do this for only one network (_centralityPlot(network1, include = "all"))_) it works fine.

Any suggestions?
Thanks,
Jan

**Comment by SachaEpskamp** [comment]
Note the bracket placement and capitalization in your examples. The following works for me:

> centralityPlot(list(network1, network2), include ="all")

**Comment by jhoelt** [comment]
Thanks for your reply. It works now, but I had to re-install everything. Weird. Thanks for this great tool, I´m really looking forward to analyze my data with it.
