### ISSUE TITLE
Please allow user to specify that node labels are not abbreviated

### ISSUE THREAD

**Issue by andrewjohnlowe** [SachaEpskamp/qgraph#3]
Hello,

Please could you enable users to specify that the node labels are not abbreviated? With a switch, perhaps? I'd rather take care of the abbreviation myself, or not have the node labels abbreviated at all. Thanks!

Best regards,

Andrew.

**Comment by SachaEpskamp** [comment]
Hi Andrew,

You can use the 'labels' argument to manually assign the labels yourself.

Best, Sacha

2015-09-04 22:20 GMT+08:00 Andrew John Lowe <notifications@github.com>:

**Comment by andrewjohnlowe** [comment]
Thanks! Didn't spot that option. Excellent package, by the way! I'm using it to visualise large correlation matrices in a high-energy particle physics analysis. This'll blow my colleagues' socks off!
