### ISSUE TITLE
clusteringPlot error when run with "list" object

### ISSUE THREAD

**Issue by jinseob2kim** [SachaEpskamp/qgraph#30]
I get clusteringPlot with 
clusteringPlot(pcorGraph)

But I see error with
clusteringPlot(list(pcorGraph))

Error in clusteringTable(..., labels = labels, standardized = standardized,  : 
  (list) object cannot be coerced to type 'double'

How can I get the clusteringPlot with multiple objects?

sincerely.

Jinseob Kim

**Comment by SachaEpskamp** [comment]
This has now been fixed!
