### ISSUE TITLE
Changing arrowhead symbol

### ISSUE THREAD

**Issue by marknovak** [SachaEpskamp/qgraph#31]
Any chance you could (explain how to) implement an option to replace the shape/symbol of the edge arrowheads with a different shape (e.g., any of the pch options of `points()`)?  I'm trying to create a graph that uses arrowheads to positive effects and circles (pch=19) for negative effects (e.g., [link](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwisuvvVuZXjAhU1FTQIHR4hA9EQjRx6BAgBEAU&url=https%3A%2F%2Fwww.researchgate.net%2Ffigure%2FSigned-digraphs-of-the-alternative-food-web-models-M-1-to-M-4-of-the-NW-Mediterranean-Sea_fig1_324222616&psig=AOvVaw3T2RDMssUZj9NUgNRaAKFP&ust=1562129941856398)).  thanks

**Comment by SachaEpskamp** [comment]
This might be more tricky than it seems. The function for drawing an arrow is here: https://github.com/SachaEpskamp/qgraph/blob/master/R/DrawArrow.R (does not use a base R plotting symbol). The hardest part here is that I would need to know exactly where a node ends and a circle on the edge end ends too, such that these ending points connect to each other. That will not be very trivial I'm afraid... so I won't pick this up any time soon.
