### ISSUE TITLE
Where can I set lambda argument in qgraph?

### ISSUE THREAD

**Issue by jaspershen** [SachaEpskamp/qgraph#32]
Hi Sacha,

First I appreciate your qgraph very much! I am now using this package for data analysis. I saw your instruction and example in this article, https://eiko-fried.com/wp-content/uploads/Epskamp-Fried-2018-Tutorial-partial-corr.pdf. However, I don't find where I can set the lamda argument. I only find the tunning and gamma argument (they are same if I don't misunderstand), so could you kindly tell me which I can set the lambda argument, or where can I find the code for you deme data in this article, https://eiko-fried.com/wp-content/uploads/Epskamp-Fried-2018-Tutorial-partial-corr.pdf. Thanks very much!

**Comment by SachaEpskamp** [comment]
Hi!

You can't set it in qgraph, as you can just use the glasso package directly for that. The EBICglasso function is only a simple wrapper around glasso to select the tuning parameter.

Best, Sacha
