### ISSUE TITLE
move packages from Imports to Suggests field [Suggestion]

### ISSUE THREAD

**Issue by nielsaka** [SachaEpskamp/qgraph#36]
I suggest reviewing the necessity of declaring so many packages under 'imports' field in DESCRIPTION. I suspect some of those packages are only necessary for certain use cases (e.g. not for mine). Having to install so many dependencies bugs me.

Just a suggestion. Needless to say (but I still say it for emphasis) the decision is the package developers.

**Comment by SachaEpskamp** [comment]
Thanks for the suggestion. Indeed I already started the process of slowly moving qgraph out of dependency hell and critically evaluating which dependencies are really needed. I already cut functionality recently, and will look more at this in the coming releases!
