### ISSUE TITLE
Does edge color really mean "positive/negative correlation" statistically?

### ISSUE THREAD

**Issue by dengxuebin** [SachaEpskamp/qgraph#37]
Hi Sacha
Recently I found all the edge color of object from "mgm" were darkgrey in qgraph. When I searched
manual of qgraph and found "posCol Color of positive edges. Can be a vector of two to indicate color of edges under ’cut’ value and color of edges over ’cut’ value." This is to say, the edge color depends on "cut" value instead of actual positive/negative correlation. I was very confused about it. Can you explain it more? Thanks a lot!

**Comment by SachaEpskamp** [comment]
mgm edges for categorical variables don't have a sign, so they are set to gray by default in the mgm package.
