### ISSUE TITLE
Confusion about centrality

### ISSUE THREAD

**Issue by Mosen111** [SachaEpskamp/qgraph#38]
Hi
When I use the centrality function, I get: OutDegree, InDegree, Closeness, Betweenness, InExpectedInfluence, OutExpectedInfluence, ShortestPathLengths, and ShortestPaths values. Surprisingly, there is no "strength" values in the output. However, when I use the centralityplot function, I get a plot of "strength". Can you please let me know why the centrality function does not output node strength values? how could one obtain numerical node strength values?

many thanks in advance,

**Comment by SachaEpskamp** [comment]
Strength is the term used for outdegree / indegree (they are the same then) in weighted undirected graphs. Hence, you can obtain the raw estimates for strength using either OutDegree or InDegree.

**Comment by Mosen111** [comment]
Thanks a lot Sacha.
