### ISSUE TITLE
error in qgraph

### ISSUE THREAD

**Issue by tjleoos** [SachaEpskamp/qgraph#39]
> library("psych")
> big5pca <- principal(cor(big5),5,rotate="promax")
> qgraph(big5pca,groups=big5groups,layout="circle",rotation="promax",minimum=0.2,
+        cut=0.4,vsize=c(1.5,10),borders=FALSE,vTrans=200,title="Big 5 PCA")
Error in qgraph(big5pca, groups = big5groups, layout = "circle", rotation = "promax",  : 
  Input is not a weights matrix or an edgelist.

**Comment by SachaEpskamp** [comment]
`library("psych")` should be `library("psychTools")`, this will be fixed in the new version!
