### ISSUE TITLE
centralityPlot with confidence intervals

### ISSUE THREAD

**Issue by ariannechr** [SachaEpskamp/qgraph#40]
Hey Sacha,

Just trying to reproduce your Figure 2 in the Supplementary Materials (i.e. 95% quantile regions plotted in centralityPlot ([Epskamp, Borsboom, Fried, 2018](https://static-content.springer.com/esm/art%3A10.3758%2Fs13428-017-0862-1/MediaObjects/13428_2017_862_MOESM1_ESM.pdf))

Bootstrap 95% CIs on centrality indices:
boot3 <- bootnet(Data, 100, default = "pcor", type = "parametric")

Plot the 95% quantile regions:
plot(boot3, statistics = c("strength","closeness","betweenness"),CIstyle = "quantiles")

Instead, I appear to be getting the node strength plot, like figure 6 (below) from the (Epskamp, Borsboom, Fried, 2018) [tutorial paper](https://link.springer.com/content/pdf/10.3758/s13428-017-0862-1.pdf)

Arianne

**Comment by diegogaldinof** [comment]
Hi, Arianne! 

I guess you need to specify the centrality measures in argument ``statistics``.

Try this:
boot3 <- bootnet(Data, 100, default = "pcor", type = "parametric", statistics = c("edge", "strength", "betweenness", "closeness"))

I hope to be contributing with your analysis.

Cheers!

**Comment by ariannechr** [comment]
thanks!

**Comment by alexp872** [comment]
Hello!

This fix doesn't work for me - I still get the node strength plot (as in Fig 6, referenced above), but I want the 95% quantile regions plotted in centralityPlot


boot1 <- bootnet(results, nCores = 8,
                 nBoots = 1000, type = 'nonparametric', statistics= c("edge", "strength","closeness","betweenness"))

plot(boot1, statistics = c("strength"),CIstyle = "quantiles")

Any help much appreciated!

**Comment by SachaEpskamp** [comment]
This is deliberatly not made possible as [bootstrapping CIs around centrality metrics is not possible](http://sachaepskamp.com/files/bootnet_Supplementary.pdf).
