### ISSUE TITLE
Interpreting Edge Weight (Partial Correlation) Magnitude

### ISSUE THREAD

**Issue by mgrugan92** [SachaEpskamp/qgraph#43]
Hi Sacha,

Firstly, thank you for making your knowledge and content on Network Analysis accessible to everyone. It is a cool analytical technique and I have enjoyed learning from your work. 

I have recently computed a regularised partial correlation network using your tutorial as a guide (Epskamp & Fried, 2018). The network contains 12 nodes and 43 edge weights (65.15% of all possible pairwise associations). The magnitude of the edge weights (partial correlations) ranges from (r = .00 to .42). 

How do you interpret the magnitude (and/or salience) of each association in the network. Is it appropriate to say that two nodes share a strong, moderate, or weak association based on the magnitude of the associated partial correlation. If so, what criteria would you employ to make such evaluations (e.g., > .10, >.30, >.50)? 

Or alternatively, is it the case that any edges remaining following the LASSO regularisation (EBIC hyperparameter = 0.5) are important (regardless of the partial correlation magnitude)?

Any advice on the above would be of great help.

Best Regards,

Michael.

**Comment by SachaEpskamp** [comment]
Hi Michael,

There aren't any real guidelines for this, also because partial correlations become weaker the more nodes you enter. I will close this topic here as it isn't really a software related issue.

Best, Sacha
