### ISSUE TITLE
qgraph.pca not available

### ISSUE THREAD

**Issue by percyd** [SachaEpskamp/qgraph#44]
Hi, I've been following all of the awesome examples of qgraph on the web and have created some great visualizations with it, thanks!
For some reason qgraph.pca is not showing up in the list of available functions. 
qgraph.loadings is available.
I'm using version 1.65 with a fresh install of R and Rstudio
I tried in R-Gui, also...
Thanks for any help you can give!
Cheers,
Percy

**Comment by SachaEpskamp** [comment]
Hi Percy,

This function has been removed from qgraph.

Best, Sacha

**Comment by percyd** [comment]
Hi Sacha, thanks...
But, what was it replaced with? There are a LOT of examples on the web of using qgraph.pca!
Thanks again!
Percy

**Comment by SachaEpskamp** [comment]
It wasn't replaced. You can still use `qgraph.loadings` however, but I removed all estimation functions (because there are better estimators in R). For PCA, I would recommend looking at the `psych` package.
