### ISSUE TITLE
centralityPlot - grouping graphs without colour

### ISSUE THREAD

**Issue by nathan-monk** [SachaEpskamp/qgraph#49]
Hi Sacha,

I am plotting centrality values for two graphs in the same panel, i.e.:

fig_list <- list(Group 1 = network1, Group 2 = network2)
fig_plot <- centralityPlot(fig_list, include = "ExpectedInfluence",
                                  labels = names, orderBy = "ExpectedInfluence",
                                  theme_bw = TRUE)

By default, this plots the groups by colour (pink and blue). I'm wanting to plot the groups by dots vs. dashes instead of colour. I've tried transferring the centrality data into ggplot via centralityTable() and doing it that way, but have found it difficult trying to reproduce the centrality plot in ggplot (I'm fairly new to ggplot). Is there an easy way?

Cheers!

**Comment by SachaEpskamp** [comment]
The `centralityPlot` function returns a ggplot object you can add things to. But the easiest probably is to just take the ggplot code from the [function](https://github.com/SachaEpskamp/qgraph/blob/master/R/centralityPlot.R) and make the adjustments you need manually.
