### ISSUE TITLE
'lty' error when number of edges equals number of nodes

### ISSUE THREAD

**Issue by carizmendi** [SachaEpskamp/qgraph#50]
[Archive.zip](https://github.com/SachaEpskamp/qgraph/files/5518642/Archive.zip)

Get ''lty' is wrong length' error when number of edges equals number of nodes.  Do not receive error if I add an extra edge to the edge list.  I've attached a a toy example with an RData file and the R code.  Hope it helps!

**Comment by SachaEpskamp** [comment]
This is because your input is a 3 x 3 matrix, which qgraph thinks is a weights matrix. Using `edgelist = TRUE` should fix this!

Best, Sacha
