### ISSUE TITLE
How do I make the edges of the network analysis diagram appear with dotted lines

### ISSUE THREAD

**Issue by threetree-wu** [SachaEpskamp/qgraph#53]
Hello，
The magazine I want to contribute cannot display the color of network analysis due to printing problems. Is there any way to replace the negative correlation edge with a dashed line to display it?

**Comment by SachaEpskamp** [comment]
Yes just use `qgraph(..., theme = "gray")`!

**Comment by threetree-wu** [comment]
Thank you for your prompt reply，I tried this argument, but found that it just turned all the colors gray. 
Whether "makeBW" can achieve the positive correlation into a solid line, negative correlation into a dotted line？

**Comment by SachaEpskamp** [comment]
You can also use the `lty` argument for that. E.g., `qgraph(wmat, ..., lty=ifelse(wmat<0,2,1))`
