### ISSUE TITLE
Warning message: Removed 2 rows containing missing values (geom_point).

### ISSUE THREAD

**Issue by lxxhy** [SachaEpskamp/qgraph#54]
hello, Sacha.

I want to ask you errors about centrality.

>` centralityPlot(Network0, include = c("Strength", "Closeness", "Betweenness"), scale = "relative", orderBy = "Strength")`
> Note: relative centrality indices are shown on x-axis rather than raw centrality indices.
> Warning message:
> Removed 2 rows containing missing values (geom_point).

This error only appears in the data containing the `threshold = TRUE`, is it related? Please reply if you have any guesses.**

**Comment by SachaEpskamp** [comment]
The warning has to do with NA centrality indices, likely due to nodes not being connected to the giant component. The note simply clarifies that the centrality metrics are standardized.

**Comment by lxxhy** [comment]
Hi Sacha,

Thank you so much for your sincere reply.
I'd like to ask you again via email about what I asked you about boot/#44
("Error in check For Remote Errors(val)" apps when running bootnet.#44).


At first, I put the code as below, and I changed it to the second code
according to your advice.

boots <- bootnet(Network, statistics = c("Strength", "Closeness",
"Betweenness"), nBoots = 1000, nCores = 4, type = "case")

Note: bootnet will store only the following statistics: Strength,
Closeness, Betweenness
Estimating sample network...
Estimating Network. Using package::function:

   - qgraph::EBICglasso for EBIC model selection
      - using glasso::glasso
   - qgraph::cor_auto for correlation computation
      - using lavaan::lavCor
      Variables detected as ordinal: D1; D2; D3; D4; D5; D6; D7; D8; D9;
      D10; D11; D12; D13; D14; D15; D16; D17; D18; D19; D20; D21; A1;
A2; A3; A4;
      A5; A6; A7; A8; A9; A10; A11; A12; A13; A14; A15; A16; A17; A18;
A19; A20;
      A21
      Bootstrapping...
      |++++++++++++++++++ | 35% ~28m 06s Error in checkForRemoteErrors(val)
      :
      one node produced an error: Maximum number of errors in bootstraps
      reached
      In addition: Warning message:
      In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal =
      penalize.diagonal, :
      A dense regularized network was selected (lambda < 0.1 * lambda.max).
      Recent work indicates a possible drop in specificity. Interpret the
      presence of the smallest edges with care. Setting threshold = TRUE will
      enforce higher specificity, at the cost of sensitivity.

boots <- bootnet(Network, statistics = c("Strength", "Closeness",
"Betweenness"), nBoots = 1000, nCores = 1, corMethod = "spearman", type =
"case")

Then I got this error.

Note: bootnet will store only the following statistics: Strength,
Closeness, Betweenness
Estimating sample network...
Estimating Network. Using package::function:


   - qgraph::EBICglasso for EBIC model selection
      - using glasso::glasso
   - qgraph::cor_auto for correlation computation
      - using lavaan::lavCor
      Variables detected as ordinal: D1; D2; D3; D4; D5; D6; D7; D8; D9;
      D10; D11; D12; D13; D14; D15; D16; D17; D18; D19; D20; D21; A1;
A2; A3; A4;
      A5; A6; A7; A8; A9; A10; A11; A12; A13; A14; A15; A16; A17; A18;
A19; A20;
      A21
      Bootstrapping...
      | | 0%Error in bootnet_correlate(data = data, corMethod = corMethod,
      corArgs = corArgs, :
      Correlation matrix is not positive definite.
      In addition: Warning message:
      In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal =
      penalize.diagonal, :
      A dense regularized network was selected (lambda < 0.1 * lambda.max).
      Recent work indicates a possible drop in specificity. Interpret the
      presence of the smallest edges with care. Setting threshold = TRUE will
      enforce higher specificity, at the cost of sensitivity.

I would really appreciate it if you could let me know if there are other
possible attempts to resolve this error.

2021년 4월 29일 (목) 오후 8:06, Sacha Epskamp ***@***.***>님이 작성:

**Comment by JoeyJoeyLI** [comment]
Hi Sacha,

I would like to inquire about the meaning of a NA centrality index. Does it indicate that the centrality analysis did not terminate normally? Additionally, I have encountered a missing value for one node in my network. Please refer to the attached picture below.

Thank you!
<img width="364" alt="截屏2023-07-11 下午12 41 34" src="https://github.com/SachaEpskamp/qgraph/assets/139199274/0590502b-91f6-4999-8509-1a8fe07d0ccb">
<img width="362" alt="截屏2023-07-11 下午12 41 54" src="https://github.com/SachaEpskamp/qgraph/assets/139199274/dca3eca4-4ed3-4035-a870-98e69eaacf8e">
