### ISSUE TITLE
Flow function - "number of rows in 'edgeConnectPoints' do not match number of edges" error

### ISSUE THREAD

**Issue by tamedf0x** [SachaEpskamp/qgraph#56]
Hi,
I'm trying use the flow function using my lasso graph as an object. However, it produces an error saying "Number of rows in 'edgeConnectPoints' do not match number of edges". The flow function works well if I use my partial correlation graph instead of the lasso graph.
Here is my code for the lasso graph:
```
Graph_lasso<-qgraph(PolyCor, cut=0, graph="glasso",layout="spring",
                    sampleSize=193, threshold=TRUE)
```

This is the code for the partial correlation graph:

`Graph_pcor<-qgraph(PolyCor, graph="pcor", layout="spring", sampleSize=nrow(Data))
`
This is the code for the flow function:

`flow(Graph_lasso,"scd",horizontal=TRUE)`

Thank you in advance!

**Comment by SachaEpskamp** [comment]
This should already have been fixed in the devel version!
