### ISSUE TITLE
Nodes of the same community not displayed next to each other

### ISSUE THREAD

**Issue by IreneBobevski** [SachaEpskamp/qgraph#57]
Hi Sacha,

I have plotted a graph of the network structure of various psychological symptoms, after using EGA to estimate the network ( my code is below). The EGA identified four distinct communities, as shown in the graph below. In the graph two of the red nodes of Community 1 are shown apart from the rest of the red nodes of this community. Is there a reason for this? Is it possible to plot the graph with all nodes of Community 1 next to each other?
 
`gega.v1 <- EGA(gcombdata.v1, model = "glasso", algorithm = "louvain")`

`gega_v1_plot <- plot(gega.v1, vsize = 7, 
                     layout = "spring", 
                     groups = as.factor(gega.v1$wc),
                     labels = colnames(gega_colnames_v1),
                     label.prop=1, label.norm="OOOOOOO")`

![image](https://user-images.githubusercontent.com/70269686/135078424-b5dc442e-69fc-47d1-8506-cd6a37872442.png)

**Comment by SachaEpskamp** [comment]
The placement algorithm is chaotic, so this can happen. Note that ds_cope is strongly connected to ds_role, so they do form a cluster. You can play around with the repulsion argument of the Fruchterman Reingold algorithm to get different layouts (although I am not sure if that is implemented in the EGA plot method).

**Comment by IreneBobevski** [comment]
Many thanks Sacha. Decreasing the repulsion slightly from the default of 1 to 0.93 worked very well:

`gega_v1_plot <- plot(gega.v1, vsize = 7, 
                     layout = "spring", 
                     repulsion=0.93,
                     groups = as.factor(gega.v1$wc),
                     labels = colnames(gega_colnames_v1),
                     label.prop=1, label.norm="OOOOOOO")`

![image](https://user-images.githubusercontent.com/70269686/135202306-6a342e54-7314-4812-8e66-52b37d7718a2.png)
