### ISSUE TITLE
Nodes overlap when layout="groups"

### ISSUE THREAD

**Issue by desphua** [SachaEpskamp/qgraph#64]
I tried to use layout="groups" but two nodes from different groups overlap each other (i.e., nodes 26 and 51 in my example below). How do I resolve this?

![image](https://user-images.githubusercontent.com/28746650/192999014-f8842d49-a991-446b-8349-ced8d527a970.png)

**Comment by SachaEpskamp** [comment]
You can use the `layout.control` argument for this:
```
library("qgraph")
adj <- matrix(1,8,8)
groups <- rep(LETTERS[1:2],each=4)
qgraph(adj, groups = groups, layout = "circular", layout.control = 0.8)
```
Best, Sacha
