### ISSUE TITLE
Legend disappears when setting edge.labels=TRUE

### ISSUE THREAD

**Issue by jmbh** [SachaEpskamp/qgraph#72]
Hi Sacha, 

Reproducible example:

library(qgraph)
p <- 10
m <- matrix(0, p, p)
m[upper.tri(m)] <- rnorm((p*(p-1))/2)
m <- m+t(m)
labels <- LETTERS[1:p]
qgraph(m, nodeNames = labels) # legend present
qgraph(m, nodeNames = labels, edge.labels=TRUE) # legend disappears

Cheers,
Jonas

**Comment by SachaEpskamp** [comment]
Hi Jonas, I cannot reproduce this, both commands show a legend for me?

**Comment by jmbh** [comment]
Indeed, I just updated qgraph which resolved this issue.

Thanks,
Jonas
