### ISSUE TITLE
Error in flow

### ISSUE THREAD

**Issue by desphua** [SachaEpskamp/qgraph#83]
I'm trying to generate a flow chart, but it keeps giving me the error:

```
Error in flow(subscales2_GGM.qgraph, "stress_Y12", horizontal = TRUE) : 
  No labels supplied

```
This is the qgraph code:
subscales2_GGM.qgraph <- qgraph(subscales2_GGM$graph, vsize=3, minimum=0.13, maximum=1, theme="colorblind", legend.cex=0.2, palette="rainbow", layout="spring", labels = seq(1:47), nodeNames=subscales2.names, groups=subscales2.grps, GLratio=1.5, repulsion=1, mar=c(1,3,1,1), color=distinctColorPalette(19))

flow(subscales2_GGM.qgraph, "stress_Y12", horizontal=TRUE)

**Comment by SachaEpskamp** [comment]
Hi! Could you make a reproducible example possibly with just some simulated data? It is hard to see what is going wrong now, but one thing could be that you define the labels using `labels = seq(1:47)` as a sequence of numbers but then use `"stress_Y12"` in the call to `flow(...)`, which is not a defined label of a node.

Kind regards,
Sacha

**Comment by desphua** [comment]
Managed to fix the problem. As you suspected, the code could not accept labels that start with a number. Once I added an alphabet in front of each label, the problem is fixed.

**Comment by desphua** [comment]
Managed to fix the problem. As you suspected, the code could not accept labels that start with a number. Once I added an alphabet in front of each label, the problem is fixed.
