### ISSUE TITLE
No way to concisely depict networks with bidirectional arrows where each direction differs in strength

### ISSUE THREAD

**Issue by Spiritspeak** [SachaEpskamp/qgraph#90]
Correlation networks have the advantage that only one edge is drawn between any two nodes; but in some cases the effect from one node to another differs from the reverse, and I'd like to be able to depict that without drawing two edges, since that's half the amount of clutter onscreen. I have tried `bidirectional=TRUE`, but this creates a single edge that does not contain any information about the individual strength of each edge that is combined into it. Could you add support for this feature?

**Comment by SachaEpskamp** [comment]
Hi! A bidirectional edge per definition is a single edge with one weight with two arrowheads. It seems to me you indicate a directed netwokr instead? I don't see how you can show this information without showing two edges. Try `parallelEdge = TRUE` for a cleaner picture perhaps.
