### ISSUE TITLE
Forcing nodes positions

### ISSUE THREAD

**Issue by ogandril** [SachaEpskamp/qgraph#92]
I want to plot two graphs with different edges but the same nodes, and I want the nodes to be at the same x-y position, so that the edges differences are easy to spot.
Is there a way to force nodes positions?

Best

Olivier

PS: I'm a big fan of qgraph! It already solved a lot of issues I had regarding graph plotting!

**Comment by SachaEpskamp** [comment]
Just use the `layout` argument in qgraph. One way is to use:

```
L <- averageLayout(input1, input2)
qgraph(input1, layout = L, ...)
qgraph(input2, layout = L, ...)
```

**Comment by ogandril** [comment]
Worked like a charm!!! Thank's A LOT.
